<div class="head"><div><h2>Website settings</h2><p>Update your branding, contact information and website content.</p></div><a class="btn" href="{{ route('home') }}" target="_blank" rel="noopener">Preview website ↗</a></div>
@if(session('status'))<div class="card settings-message" role="status">{{ session('status') }}</div>@endif
@if($errors->any())<div class="card settings-message" role="alert">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<form class="card settings-form" action="{{ route('admin.settings.update') }}" method="POST" enctype="multipart/form-data">@csrf @method('PUT')
    <section class="settings-section"><h3>Branding & contact</h3><p class="settings-hint">These details appear across your website.</p>
    <div class="two"><div class="f"><label for="site_title">Site title</label><input id="site_title" name="site_title" required maxlength="100" value="{{ old('site_title', $siteSettings['site_title']) }}"></div><div class="f"><label for="contact_email">Contact email</label><input id="contact_email" name="contact_email" type="email" required maxlength="255" value="{{ old('contact_email', $siteSettings['contact_email']) }}"></div></div>
    <div class="f"><label for="site_description">Site description</label><textarea id="site_description" name="site_description" rows="3" required maxlength="1000">{{ old('site_description', $siteSettings['site_description']) }}</textarea><small class="settings-hint">Default description for search results. Chapter SEO fields take priority on chapter pages.</small></div>
    <div class="settings-logo"><div class="settings-logo-preview">@include('website.partials.brand-logo')<b>{{ $siteSettings['site_title'] }}</b></div><div class="f"><label for="logo">Upload logo</label><input id="logo" name="logo" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><small class="settings-hint">PNG, JPG, WebP or GIF · Up to 2 MB, 3000 × 3000 pixels. Leave empty to keep your logo.</small>@if($siteLogoUrl)<label class="settings-remove"><input name="remove_logo" type="checkbox" value="1" @checked(old('remove_logo'))> Remove custom logo</label>@endif</div></div>
    </section>
    <section class="settings-section"><h3>Homepage content</h3><div class="f"><label for="home_title">Homepage heading</label><input id="home_title" name="home_title" required maxlength="255" value="{{ old('home_title', $siteSettings['home_title']) }}"></div><div class="f"><label for="home_description">Homepage introduction</label><textarea id="home_description" name="home_description" rows="4" required maxlength="3000">{{ old('home_description', $siteSettings['home_description']) }}</textarea></div></section>
    <section class="settings-section"><h3>Page & footer content</h3><div class="f"><label for="about_content">About page content</label><textarea id="about_content" name="about_content" rows="6" required maxlength="10000">{{ old('about_content', $siteSettings['about_content']) }}</textarea></div><div class="f"><label for="contact_description">Contact page introduction</label><textarea id="contact_description" name="contact_description" rows="3" required maxlength="3000">{{ old('contact_description', $siteSettings['contact_description']) }}</textarea></div><div class="f"><label for="footer_description">Footer description</label><textarea id="footer_description" name="footer_description" rows="3" required maxlength="3000">{{ old('footer_description', $siteSettings['footer_description']) }}</textarea></div></section>
    <div class="settings-actions"><span class="settings-hint">Saved changes appear immediately on the website.</span><button class="btn pri" type="submit">Save settings</button></div>
</form>
